# Generated by Django 3.1.1 on 2021-07-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='comments',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
