# Generated by Django 3.1.1 on 2021-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
