# Generated by Django 3.1.1 on 2021-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
